# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: spayeur <spayeur@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/21 16:58:11 by spayeur           #+#    #+#              #
#    Updated: 2023/03/28 21:18:49 by spayeur          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.9'

services:
    deploy:
        build:
          context: .
          dockerfile: images/deploy/Dockerfile
          args:
            - PORT=${REACT_PORT}
            - REACT_APP_NESTJS_PORT=${NESTJS_PORT}
            - REACT_APP_OAUTH_42_UID=${OAUTH_42_UID}
            - REACT_APP_OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
            - PORT=${NESTJS_PORT}
            - DATABASE_URL=postgresql://${PGSQL_USER}:${PGSQL_PASSWORD}@pgsql:${PGSQL_PORT}/${PGSQL_DATABASE}
            - NESTJS_JWT_SECRET
            - OAUTH_42_UID
            - OAUTH_42_SECRET
            - OAUTH_CALLBACK_URL
        container_name: server
        ports:
            - ${NESTJS_PORT}:${NESTJS_PORT}
        environment:
            - PORT=${REACT_PORT}
            - REACT_APP_NESTJS_PORT=${NESTJS_PORT}
            - REACT_APP_OAUTH_42_UID=${OAUTH_42_UID}
            - REACT_APP_OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
            - PORT=${NESTJS_PORT}
            - DATABASE_URL=postgresql://${PGSQL_USER}:${PGSQL_PASSWORD}@pgsql:${PGSQL_PORT}/${PGSQL_DATABASE}
            - NESTJS_JWT_SECRET
            - OAUTH_42_UID
            - OAUTH_42_SECRET
            - OAUTH_CALLBACK_URL
        networks:
            - ft_transcendence
        restart: unless-stopped
        depends_on:
            - pgsql

    pgsql:
        image: postgres:15.2-alpine3.17
        container_name: pgsql
        environment:
            - PGPORT=${PGSQL_PORT}
            - POSTGRES_USER=${PGSQL_USER}
            - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
            - POSTGRES_DATABASE=${PGSQL_DATABASE}
        networks:
            - ft_transcendence
        restart: unless-stopped


    # prisma_studio:
    #     build: images/prisma_studio
    #     container_name: prisma_studio
    #     ports:
    #         - ${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}
    #     environment:
    #         - PORT=${PRISMA_STUDIO_PORT}
    #         - DATABASE_URL=postgresql://${PGSQL_USER}:${PGSQL_PASSWORD}@pgsql:${PGSQL_PORT}/${PGSQL_DATABASE}
    #     networks:
    #         - ft_transcendence
    #     volumes:
    #         - nestjs_app:/app
    #     restart: unless-stopped

networks:
    ft_transcendence:
        name: ft_transcendence
